# Generated by Django 4.0.2 on 2022-03-30 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_userorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='orders',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
