# Generated by Django 4.0.2 on 2022-05-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cart_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorders',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='userorders',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
    ]
