# Generated by Django 4.0.2 on 2022-05-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_userorders_orderdate_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemimg',
            field=models.ImageField(default='item_images/default.png', upload_to='item_images'),
        ),
    ]
